name: Demo CI (ephemeral)
on: [push, pull_request]
jobs:
  ci:
    uses: NixLine-org/.github/.github/workflows/nixline-ci.yml@stable
    with:
      channel: stable
      packs: gh-actions,precommit,editorconfig,codeowners,security,license,sbom,dependabot,flake-update
      sync_mode: ephemeral
