name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  nixline-ci:
    uses: NixLine-org/.github/.github/workflows/nixline-ci.yml@stable
    with:
      channel: stable
      # Customize packs - exclude security for demo purposes
      packs: "editorconfig,codeowners,license,precommit,dependabot"
