name: Verify All NixLine Workflows
on:
  workflow_dispatch: {}
  push:
    branches: [main]

# Default: read-only for all jobs
permissions:
  contents: read
  pull-requests: none

jobs:
  ci:
    uses: NixLine-org/.github/.github/workflows/nixline-ci.yml@stable
    with:
      channel: stable
      packs: gh-actions,precommit,editorconfig,codeowners,security,license,sbom,dependabot,flake-update
      sync_mode: ephemeral

  sbom:
    uses: NixLine-org/.github/.github/workflows/nixline-sbom.yml@stable

  flake_update:
    # Allow writes only for this job
    permissions:
      contents: write
      pull-requests: write
    uses: NixLine-org/.github/.github/workflows/nixline-flake-update.yml@stable
    with:
      pr-title: "chore(nix): verify flake update"
      pr-labels: "test, nix"

  dependabot_automerge:
    uses: NixLine-org/.github/.github/workflows/nixline-dependabot-automerge.yml@stable
    with:
      allow_minor_patch: "true"
      allow_security_updates: "true"

  policy_check:
    uses: NixLine-org/.github/.github/workflows/nixline-policy-flake-lock-only.yml@stable
